# Generated by Django 5.1.5 on 2025-02-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание универа, важной информации о нём', verbose_name='Описание')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('number', models.CharField(help_text='Введите номер телефона в формате +XXX (XX) XXX-XX-XX', max_length=50, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('website', models.CharField(max_length=150, verbose_name='Оффициальный сайт')),
                ('twitter', models.CharField(max_length=150, verbose_name='twitter')),
                ('facebook', models.CharField(max_length=150, verbose_name='facebook')),
                ('linkedin', models.CharField(max_length=150, verbose_name='linkedin')),
                ('instagram', models.CharField(max_length=150, verbose_name='instagram')),
                ('youtube', models.CharField(max_length=150, verbose_name='youtube')),
                ('telegram', models.CharField(max_length=150, verbose_name='telegram')),
                ('bysite', models.BooleanField(default=False, verbose_name='Программы от нас')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univers.country', verbose_name='Страна')),
                ('directions', models.ManyToManyField(to='univers.direction', verbose_name='Направления')),
                ('subjects', models.ManyToManyField(to='univers.subject', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Универ',
                'verbose_name_plural': 'Универы',
            },
        ),
    ]
