# Generated by Django 5.1.5 on 2025-02-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='univer',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='univer',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='univer',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='univer',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='univer',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='univer',
            name='youtube',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='youtube'),
        ),
    ]
