# Generated by Django 5.1.6 on 2025-02-05 17:10

import univers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0002_alter_univer_email_alter_univer_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='univer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=univers.models.univer_photo_path, verbose_name='Фото'),
        ),
    ]
