# Generated by Django 5.1.6 on 2025-02-05 17:15

import univers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0003_univer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer',
            name='photo',
            field=models.ImageField(default='', upload_to=univers.models.univer_photo_path, verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
