# Generated by Django 5.1.5 on 2025-01-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_key',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='premium.license'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='licensed',
            field=models.BooleanField(default=False, verbose_name='Лицензирован'),
        ),
    ]
