# Generated by Django 5.1.5 on 2025-01-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_license_key'),
        ('premium', '0002_alter_license_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premium.license', verbose_name='Ключ лицензии'),
        ),
    ]
