# Generated by Django 5.1.5 on 2025-01-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'План', 'verbose_name_plural': 'Планы'},
        ),
        migrations.AlterModelOptions(
            name='timelimit',
            options={'verbose_name': 'Срок', 'verbose_name_plural': 'Сроки'},
        ),
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='license',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.plan', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='license',
            name='time_limit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.timelimit', verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timelimit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
