# Generated by Django 5.1.5 on 2025-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_alter_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(blank=True, default='pld22-6n4nk-k5j00-7ec03-8335l', max_length=100, verbose_name='Ключ'),
        ),
    ]
