# Generated by Django 5.1.5 on 2025-02-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_alter_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Ключ'),
        ),
    ]
