# Generated by Django 5.1.6 on 2025-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_alter_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
